services:
  mysql:
    image: mysql:8.0
    container_name: estudioenb_mysql
    environment:
      MYSQL_ROOT_PASSWORD: rootpass
      MYSQL_DATABASE: estudioenb
      MYSQL_USER: estudioenb
      MYSQL_PASSWORD: estudioenbpass
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
volumes:
  mysql_data: